# This Dockerfile is used to test that that CLI tool
# works when only the 2.0 SDK is installed in the environment

FROM microsoft/dotnet:2.0-sdk-nanoserver-sac2016
WORKDIR /app
COPY . .
ENTRYPOINT .\test.ps1