#!/bin/sh
# Update version and changelog, including any changes in the commit.
# Copy this file under .git/hooks to enable

github_changelog_generator
PROJECT_VERSION=$(gitversion -showvariable NugetVersionV2)
cd dotnet-setversion
dotnet restore
dotnet setversion $PROJECT_VERSION
cd ..
git add CHANGELOG.md
git add dotnet-setversion/dotnet-setversion.csproj