# This Dockerfile is used to test that that CLI tool
# works when only the 2.0 SDK is installed in the environment

FROM microsoft/dotnet:2.0-sdk
WORKDIR /app
COPY . .
RUN chmod +x ./test.sh
ENTRYPOINT ./test.sh